### ISSUE TITLE
大佬 何时开源代码

### ISSUE THREAD

**Issue by NICECPU** [dalision/ModalBiasAVSR#1]
大佬 何时开源代码

**Comment by dalision** [comment]
Sorry, these days I am quite busy as a bee. Once I have free time, I will get it ready. If you are rush to use，here is a baseline&nbsp;https://github.com/mispchallenge/MISP-ICME-AVSR. It is essy to reproduce our MDA-KD and MS-adapter based on this.



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月24日(周一) 中午11:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [dalision/ModalBiasAVSR] 大佬 何时开源代码 (Issue #1)




 
大佬 何时开源代码
